[programs.devnet]
cawproject = "8k8G96QMdbyiA62N72irSqArSS7DfUW2gZN4StN9afGH"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/lohrndorf/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
